### ISSUE TITLE
Update to 7.1.0 along with Silicon support

### ISSUE THREAD

**Issue by Sadmansamee** [YAtechnologies/GoogleMaps-SP#37] opened 2022-10-02 21:53 UTC

**Comment by karimhm** [comment] 2022-10-14 00:47
Check release [7.1.0](https://github.com/YAtechnologies/GoogleMaps-SP/releases/tag/7.1.0)

**Comment by karimhm** [comment] 2022-10-14 00:48
Partially duplicate of #22

**Closed by karimhm** 2022-10-14 00:48 UTC
